[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ebm-at"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
ebm-at = "ebm_at.main:main"

[tool.setuptools.packages.find]
where = ["src"]